version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always  # Pastikan restart ditulis tanpa indentasi lebih
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=nama_database
      - MYSQL_USER=nama_user
      - MYSQL_PASSWORD=your_user_password
    networks:
      - laravel

  laravelapp:
    container_name: laravelapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - laravel

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always  # Pastikan restart ditulis dengan benar
    ports:
      - "8086:80"
    depends_on:
      - mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
