# Menggunakan image Nginx resmi dari Docker Hub
FROM nginx:latest

# Menyalin file HTML ke dalam direktori default Nginx
COPY ./html /usr/share/nginx/html/

# Mengekspos port 80 agar bisa diakses dari luar
EXPOSE 80
```
