# Menggunakan image Nginx resmi dari Docker Hub
FROM nginx:latest

# Menyalin file HTML ke dalam direktori default Nginx
COPY ./html /usr/share/nginx/html/

# Mengekspos port 80 agar bisa diakses dari luar
EXPOSE 80AINER:
![gambardocker] (https://drive.google.com/uc?id=1vbabcrSyPvQW466Syh6eB7VMdATivKiA)
